{
 "title": "RAID and SSD",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "raid_host",
    "label": "Raid Host",
    "query": "SHOW TAG VALUES FROM raid_telegraf WITH KEY=host"
   },
   {
    "name": "zpool_host",
    "label": "Zpool Host",
    "query": "SHOW TAG VALUES FROM zpool WITH KEY=host"
   }
  ]
 },
 "panels": [
  { "title": "SSD Wear Out", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SSD Wear Out Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smart_attribute",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "Wear_Leveling_Count" },
      { "condition": "OR", "key": "name", "operator": "=", "value": "Available_Reservd_Space" }
     ]
    }
   ]
  },
  { "title": "RAID Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Firmware of $raid_host",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "$tag_host - $tag_device",
     "groupBy": [
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "firmware" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "firmware" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$raid_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAID alert graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "predictive_failure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_device",
     "select": [
      [
       { "params": [ "health" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAID Disk firmware failed graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "firmware" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "firmware", "operator": "=~", "value": "/Failed/" },
      { "condition": "AND", "key": "host", "operator": "!=", "value": "pve-6" }
     ]
    }
   ]
  },
  {
   "title": "RAID Media error graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "media_error" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAID Other error graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "other_error" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAID Disk SMART alert graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "smart_alert" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host", "operator": "!=", "value": "pve-6" },
      { "condition": "AND", "key": "smart_alert", "operator": "!=", "value": "No" }
     ]
    }
   ]
  },
  {
   "title": "Zpool info for $zpool_host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "zpool_host",
   "targets": [
    {}
   ]
  },
  {
   "title": "Health for $zpool_host",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pool",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool",
     "query": "SELECT mean(\"health\") FROM \"zpool\" WHERE (\"host\" =~ /^$zpool_host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "health" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$zpool_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Errors for $zpool_host",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_pool - $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "pool" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "zpool_device",
     "query": "SELECT mean(\"health\") FROM \"zpool\" WHERE (\"host\" =~ /^$zpool_host$/) AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "read_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "read_errors" ], "type": "alias" }
      ],
      [
       { "params": [ "write_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "write_errors" ], "type": "alias" }
      ],
      [
       { "params": [ "checksum_errors" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "checksum_errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$zpool_host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAID Failure for $raid_host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "repeat": "raid_host",
   "targets": [
    {}
   ]
  },
  {
   "title": "Predictive Failure for $raid_host",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raid_telegraf",
     "select": [
      [
       { "params": [ "predictive_failure" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$raid_host$/" }
     ]
    }
   ]
  }
 ]
}